# Generated by Django 5.2.4 on 2025-07-24 03:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=7, validators=[django.core.validators.MinLengthValidator(2)])),
                ('views', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
