# Generated by Django 5.2.4 on 2025-07-26 15:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseplate',
            name='number',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
